version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    # build: 
    #   context: ./backend/database
    #   dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    container_name: backend
    hostname: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_URL=${BACKEND_URL}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - PORT=${PORT}
    volumes:
      - /app/node_modules
      - ./backend:/app
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - db
  # nginx:
  #   container_name: nginx
  #   hostname: nginx
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3050:80
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - example-network
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./nginx/logs:/var/log/nginx
  #     - ./frontend/dist:/usr/share/nginx/html
  #     - ./backend/dist:/usr/share/nginx/html/api