version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    build: 
      context: ./backend/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASS: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: witty-data-todo
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=witty-data-todo
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/witty-data-todo
      - JWT_SECRET=secret
      - FRONTEND_URL=http://localhost:8080
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=8080
      - BACKEND_URL=http://localhost:3000
      - BACKEND_HOST=localhost
      - BACKEND_PORT=3000