export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS";
export const GET_MY_PROFILE_FAIL = "GET_MY_PROFILE_FAIL";
export const UPDATE_MY_PROFILE_SUCCESS = "UPDATE_MY_PROFILE_SUCCESS";
export const UPDATE_MY_PROFILE_FAIL = "UPDATE_MY_PROFILE_FAIL";
export const UPDATE_MY_PASSWORD_SUCCESS = "UPDATE_MY_PASSWORD_SUCCESS";
export const UPDATE_MY_PASSWORD_FAIL = "UPDATE_MY_PASSWORD_FAIL";
export const UPDATE_MY_PROFILE_PICTURE_SUCCESS = "UPDATE_MY_PROFILE_PICTURE_SUCCESS";
export const UPDATE_MY_PROFILE_PICTURE_FAIL = "UPDATE_MY_PROFILE_PICTURE_FAIL";

export const GET_ALL_TODOS_SUCCESS = "GET_ALL_TODOS_SUCCESS";
export const GET_ALL_TODOS_FAIL = "GET_ALL_TODOS_FAIL";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAIL = "GET_TODO_FAIL";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAIL = "CREATE_TODO_FAIL";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";
export const GET_SHARED_TODO_SUCCESS = "GET_SHARED_TODO_SUCCESS";
export const GET_SHARED_TODO_FAIL = "GET_SHARED_TODO_FAIL";
export const DELETE_SHARED_TODO_SUCCESS = "DELETE_SHARED_TODO_SUCCESS";

